### ISSUE TITLE
Suggestion for Drone names: "Freedom Dispensers"

### ISSUE THREAD

**Issue by WaldoTheRanger** [Grobobobo/ayy-lmao-lwotc-prototype#18]
Cause you know, 'Merica sending out drone strikes is the same thing as making democracy.

**Comment by Grobobobo** [comment]
Drone names are already taken as Amazon pain deliery/Amazon torture delivery. Sorry, I should probably update the Readme file.

**Comment by WaldoTheRanger** [comment]
Oh that's fine. That's a much better name anyways lol.
